### ISSUE TITLE
Fails when use synchronize module

### ISSUE THREAD

**Issue by luismanolo** [drone-plugins/drone-ansible#48]
Hi.

First I look in: https://discourse.drone.io/search?q=synchronize

My ansible task are:

```
    - name: Sync bot files
      ansible.posix.synchronize:
        src: "{{code_source}}/{{item}}"
        dest: "{{code_dest}}"

      loop:
        - "bot"
        - "config"
        - "data"
        - "hooks"
        - "images"
        - "libs"
        - "package.json"
        - "yarn.lock"
        - "index.js"
```

First I install ansible.posix from ansible galaxy in .drone.yml

```
- name: Deploy whith Ansible
  image: plugins/ansible:latest
  settings:
    ...
    galaxy: .ansible/galaxy.yml

```

And this is the log:

```
failed: [host](item=bot) => {"ansible_loop_var": "item", "changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh='/usr/bin/ssh -S none -i /tmp/privateKey534998518 -o Port=8822 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' --out-format='<<CHANGED>>%i %n%L' /bot admin@host:/opt/servidor/", "item": "bot", "msg": "Warning: Permanently added '[host]:8822,[82.223.100.241]:8822' (ECDSA) to the list of known hosts.\r\nrsync: [sender] change_dir \"/opt/servidor\" failed: No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=v3.13.0_rc2-264-g725ac7fb]\n", "rc": 23}
```
Tip: hostname and root dir are modified in the message

Many thanks
