### ISSUE TITLE
No docs?

### ISSUE THREAD

**Issue by hijak** [drone-plugins/drone-ansible#6]
Hi

how come i cannot see this on the plugin page also there are no docs on how to use.

With version 1 and cronjobs i can use this to replace my awx instance

**Comment by tboerger** [comment]
Right, we totally forgot to write some docs for that, in the meantime, this is how I'm using it with 0.8.x:

```
  ansible-check:
    image: plugins/ansible:1
    pull: true
    secrets: [ additional_var ]
    playbook: ansible/playbook.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
    syntax_check: true
    when:
      event: [ pull_request ]

  ansible-apply:
    image: plugins/ansible:1
    pull: true
    secrets: [ additional_var, ansible_private_key, ansible_vault_password ]
    playbook: ansible/playbook.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
    when:
      event: [ push, tag ]
```

**Comment by whysthatso** [comment]
>   ansible-apply:
>     image: plugins/ansible:1
>     pull: true
>     secrets: [ additional_var, ansible_private_key, ansible_vault_password ]
>     playbook: ansible/playbook.yml
>     galaxy: ansible/requirements.yml
>     inventory: ansible/inventory
>     when:
>       event: [ push, tag ]
> ```


would this be on the main level in the drone.yml file? as in:

```
kind: pipeline
name: default

ansible-apply:
...
```

**Comment by tboerger** [comment]
My comment above is the 0.8 syntax, not directly 1.0

**Comment by darkmattercoder** [comment]
So how is this then meant to be used with 1.0?

**Comment by tboerger** [comment]
Exactly like all the other plugins, just put the variables within the `settings` block:

```yaml
---
kind: pipeline
name: default

steps:
- name: ansible-check
  image: plugins/ansible:1
  environment:
    additional_var:
      from_secret: additional_var
    another_var: foo
  settings:
    playbook: ansible/playbook.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
    syntax_check: true
  when:
    event:
    - pull_request

- name: ansible-apply
  image: plugins/ansible:1
  environment:
    additional_var:
      from_secret: additional_var
    another_var: foo
  settings:
    playbook: ansible/playbook.yml
    galaxy: ansible/requirements.yml
    inventory: ansible/inventory
    private_key:
      from_secret: ansible_private_key
    vault_password:
      from_secret: ansible_vault_password
  when:
    event:
    - push
    - tag

---
kind: secret

data:
  ansible_private_key: YOUR_ENCRYPTED_VALUE
  ansible_vault_password: YOUR_ENCRYPTED_VALUE
  additional_var: YOUR_ENCRYPTED_VALUE
```
